# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'choco install -y golang ;
      choco install -y mingw ;
      refreshenv ;
      copy native-powershell\host.h .\powershell\ ;
      copy native-powershell\x64\Release\psh_host.dll . ;
      copy native-powershell\x64\Release\psh_host.dll .\powershell\ ;
      mkdir c:\go_tmp;
      $env:GOPATH="c:\go_tmp";
      $env:GOBIN=$env:GOPATH + "\bin";
      write-host $env:GOBIN $pwd $env:GOPATH $env:GOROOT;
      dir . ;
      go get . ;
      go build -o test.exe .;
      dir .;'
# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(Build.SourcesDirectory)'
#     contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/?(*.exe|*.dll|*.pdb)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
# run tests
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '.\test.exe -command .\\tests\t1.ps1 -command .\\tests\\t2.ps1'